# Generated by Django 3.2.9 on 2021-12-14 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('organizer', models.CharField(max_length=150)),
                ('organizer_type', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('Enter a valid email')])),
                ('number_of_people', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999, 'Too much people')])),
                ('event_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
