# Generated by Django 3.2.9 on 2021-12-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
