# Generated by Django 3.2.9 on 2021-12-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211217_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(max_length=40),
        ),
    ]
